name: .NET CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-60-234-145.eu-north-1.compute.amazonaws.com << EOF
        cd /home/ec2-user/VoyagerApi
        git pull origin main
        dotnet publish -c Release -o /var/www/voyager
        sudo systemctl restart voyager.service
        EOF
